ARG UBUNTU_VERSION=24.04

#
# Docker builder stage (CPU-only, no CUDA).
#
FROM ubuntu:${UBUNTU_VERSION} AS builder

ARG COLMAP_GIT_COMMIT="release/3.10"
ARG GLOMAP_GIT_COMMIT=main
ENV QT_XCB_GL_INTEGRATION=xcb_egl

# Prevent stop building ubuntu at time zone selection.
ENV DEBIAN_FRONTEND=noninteractive

# Prepare and empty machine for building.
RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        git \
        cmake \
        ninja-build \
        build-essential \
        libboost-program-options-dev \
        libboost-filesystem-dev \
        libboost-graph-dev \
        libboost-system-dev \
        libeigen3-dev \
        libflann-dev \
        libfreeimage-dev \
        libmetis-dev \
        libgoogle-glog-dev \
        libgtest-dev \
        libsqlite3-dev \
        libglew-dev \
        qtbase5-dev \
        libqt5opengl5-dev \
        libcgal-dev \
        libceres-dev \
        libsuitesparse-dev \
        libatlas-base-dev

# Build and install COLMAP (without CUDA).
RUN git clone https://github.com/colmap/colmap.git
RUN cd colmap && \
    git fetch https://github.com/colmap/colmap.git ${COLMAP_GIT_COMMIT} && \
    git checkout FETCH_HEAD && \
    mkdir build && \
    cd build && \
    cmake .. -GNinja -DCMAKE_CUDA_ARCHITECTURES=OFF \
        -DCMAKE_INSTALL_PREFIX=/colmap_installed && \
    ninja install

# Build and install GLOMAP
WORKDIR /glomap
COPY ./cmake /glomap/cmake
COPY ./glomap /glomap/glomap
COPY ./CMakeLists.txt /glomap/CMakeLists.txt

RUN mkdir /glomap/build
RUN cd /glomap/build && \
    cmake .. -GNinja -DCMAKE_INSTALL_PREFIX=/colmap_installed && \
    ninja install

#
# Docker runtime stage.
#
FROM ubuntu:${UBUNTU_VERSION} AS runtime

# Minimal dependencies to run COLMAP binary compiled in the builder stage.
# Note: this reduces the size of the final image considerably, since all the
# build dependencies are not needed.
RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        libboost-filesystem1.83.0 \
        libboost-program-options1.83.0 \
        libc6 \
        libfreeimage3 \
        libgcc-s1 \
        libgl1 \
        libglew2.2 \
        libgoogle-glog0v6 \
        libceres2 \
        libsuitesparse-dev \
        libatlas3-base \
        libqt5core5a \
        libqt5gui5 \
        libqt5widgets5 \
        libmetis5 \
        libopengl0

RUN apt update && apt install -y --no-install-recommends --no-install-suggests python3 python3-pip
RUN pip3 install --break-system-packages numpy

RUN pip3 install --break-system-packages scipy

# # Copy all files from /colmap_installed/ in the builder stage to /usr/local/ in
# # the runtime stage. This simulates installing COLMAP in the default location
# # (/usr/local/), which simplifies environment variables. It also allows the user
# # of this Docker image to use it as a base image for compiling against COLMAP as
# # a library. For instance, CMake will be able to find COLMAP easily with the
# # command: find_package(COLMAP REQUIRED).
COPY --from=builder /colmap_installed/ /usr/local/
COPY ./docker/process-dataset.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/process-dataset.sh

WORKDIR /scripts
COPY ./scripts/python/sparse_to_ply.py /scripts/
COPY ./scripts/python/binary_to_text_converter.py /scripts/
COPY ./scripts/python/export_calibration.py /scripts/

